language: rust
# We use OSX so that we can get a reasonably up to date version of SQLCipher.
# (The version in Travis's default Ubuntu Trusty is much too old).
os: osx
osx_image:
  - xcode10
before_install:
  - brew install sqlcipher --with-fts
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  # Test with 1. only default features on, 2. no features on, 3. all features on for the crates
  # where this is a sensible request, and the supported configs for the others.
  - cargo test --all --verbose
  - cargo test --all --no-default-features --verbose
  # note: -p doesn't work correctly in conjunction with --all-features,
  # but manifest-path works https://github.com/rust-lang/cargo/issues/5364
  - |
    # Test the crates that actually work with --all-features (everything except components/places and logins-sql)
    for crate in "fxa-client" "sync15-adapter" "components/support/sql" "components/support/ffi"; do
      cargo test --manifest-path ./$crate/Cargo.toml --all-features --verbose
    done
  - |
    # Test the crates that have separate sqlcipher and bundled features.
    for crate in "logins-sql" "components/places"; do
      cargo test --manifest-path ./$crate/Cargo.toml --features 'bundled' --verbose
      cargo test --manifest-path ./$crate/Cargo.toml --features 'sqlcipher' --verbose
    done


jobs:
  include:
    - stage: iOS GitHub Release
      if: tag IS present
      rust: beta
      osx_image: xcode10
      script: ./scripts/travis-ci-ios.sh
      deploy:
        provider: releases
        api_key:
          secure: PEbRLdoGVRgx6jlfvp8LzG/SRbVspWkVn3jpjkdy7jjeZ/BHsy8LSQhw37IcydqrtmCFPJBVLx1Uw0cj4H7qfVD5eSg7m6L/mXIJ+pXmhxtGVlD2IF+sNQDPgWs8DZ4diHkSntw5oSekvisT5yi3IaTP/2y9LvLBB9oJnZtaYT27Rv0B8hQN0/Etfr69i6yhNwlcfuBJ0BmVN2gMNCPydR9Xeq050AEpsVoPkFL3m5Xy7n6sUJ/DAOM0lBr4hUp2jP5ciPd3iwo1fndGvuzVFpxGdnH2DSHgD4mo2AF8vcrecr9Fkax9yxMHC5Ua2+9c4Z69fx19rP8DyKsJDR8wmPIa9fwEabgEmgTu4HRNC6Y9VCGuM7CTZMTv1iVwdV3q33K9eJtI4tBjwQyaon9owVrHBZQXB4+KqP2/Id/v0PDp3WhEN9YQQGn/HF+IvcjTMDvdkaj3q34pqbocfOpWFcTO83aQX/JYkYHKq0r1mGrPDKfTrdIBUg26jtrI64KflyXENOvU95jW3TfcwljOOsXnuI2Owov619CqJXpvyJ62CAoagRFdPRbi3VARC4mGZt/PBz1FxlDWydOMmJnK242RXapAWcRMsEVK7Mowj/+IFSD4OTF57aP66gkn4tNh/5qx0RPcwcMEpFPM9bTim3vecN15dB0f5MZelkbr7Gw=
        file: FxAClient.framework.zip
        skip_cleanup: true
        overwrite: true
        name: FxA SDK
        on:
          tags: true
